import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Build Trust",
  description: "Generated by create next app",
};

// Import font
const notoSans = Noto_Sans({
  variable: "--font-noto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSans.variable}>
      <body className="font-sans">
        <div className="w-full h-full">{children}</div>
      </body>
    </html>
  );
}
